export const corporateData = [
  {
    id: 1,
    text: "Occupational health screening",
  },
  {
    id: 2,
    text: "Basic Domestic Staff",
  },
  {
    id: 3,
    text: "Standard Domestic Staff",
  },
  {
    id: 4,
    text: "Pre employment tests",
  },
  {
    id: 5,
    text: "Food handlers",
  },
  {
    id: 6,
    text: "Cardiac Screening",
  },
  {
    id: 7,
    text: "Prenuptial Screening",
  },
  {
    id: 8,
    text: "Cervical Screening",
  },
];

export const individualData = [
  {
    name: "Support Staff package (mini)",
    items: [
      "PCV",
      "Hepatitis B Surface Antigen (HBsAg) Rapid",
      "HIV I & II Rapid",
      "BHCG- Qualitative (Pregnancy Test)",
      "Widal test",
      "Sputum AFB - Tuberculosis test",
    ],
  },
  {
    name: "Support Staff package (maxi)",
    items: [
      "Hb Electrophoresis /Genotype (Quantitative)",
      "Full blood count",
      "Widal test",
      "Hepatitis B Surface Antigen (HBsAg) Rapid",
      "HIV I & II Antibody",
      "BHCG- Qualitative (Pregnancy Test)",
      "Hepatitis C Virus Ab (Rapid)",
      "Sputm AFB - Tuberculosis test",
    ],
  },
  {
    name: "Cardiac Screen",
    items: [
      "Creatine Kinase-MB (CK-MB)",
      "Lipid Profile (Lipogram)",
      "Kidney Function Test",
      "Troponin-T",
      "D – Dimer",
    ],
  },
  {
    name: "Blue-day Package",
    items: [
      "Erythrocyte Sedimentation Rate (ESR)",
      "Full Blood Count",
      "Malaria (Thick and Thin Films)",
      "WIDAL (Typhoid Test)",
      "Stool Microscopy",
      "Urinalysis",
      "Sputum AFB - Tuberculosis test",
    ],
  },
  {
    name: "Social package",
    items: [
      "Full Blood Count",
      "Malaria (Thick and Thin Films)",
      "WIDAL (Typhoid Test)",
      "Urinalysis",
      "Hepatitis B Surface Antigen (HBsAg) Rapid",
      "HIV I & II Rapid",
      "Syphilis Screening",
      "Neisseria Gonorrhea Rapid (Detection)",
    ],
  },
  {
    name: "Vitality package (Basic)",
    items: [
      "Fasting Blood Sugar (FBS)",
      "Total Cholesterol",
      "Full Blood Count",
      "Urinalysis",
      "Liver Function Test (AST/ALT)",
      "Kidney Function Test (Urea/Creatinine)",
    ],
  },
  {
    name: "Emerald package (mini)",
    items: [
      "Fasting Blood Sugar (FBS)",
      "Lipid Profile (Lipogram)",
      "Uric Acid",
      "Full Blood Count",
      "Thyroid Stimulating Hormone (TSH)",
      "Stool Microscopy",
      "Urinalysis",
      "Liquid Based Cytology (LBC)",
      "Liver Function Test (AST/ALT)",
      "Kidney Function Test (Urea/Creatinine)",
    ],
  },
  {
    name: "Emerald package (maxi)",
    items: [
      "HbA1C",
      "Inorganic Phosphate",
      "Lipid Profile (Lipogram)",
      "Liver Function Test",
      "Kidney Function Test",
      "Calcium",
      "Uric Acid",
      "Thyroid Function Test (Free T3, Free T4,TSH)",
      "Full Blood Count",
      "C-Reactive Protein (CRP)",
      "Hepatitis B Surface Antigen (HBsAg) Rapid",
      "HIV I & II Rapid",
      "Hepatitis C Virus Ab (Rapid)",
      "Stool Occult Blood",
      "Stool Microscopy",
      "Urinalysis",
      "Liquid Based Cytology (LBC)",
    ],
  },
  {
    name: "Pre-Nuptial",
    items: [
      "Blood Grouping (ABO & Rh Typing)",
      "Hb Electrophoresis /Genotype (Quantitative)",
      "Hepatitis B Surface Antigen (HBsAg) Rapid",
      "HIV I & II Rapid",
      "BHCG- Qualitative (Pregnancy Test)",
    ],
  },
  {
    name: "Emerald fertility profile (mini)",
    items: [
      "Estradiol",
      "Follicule Stimulating Hormone (FSH)",
      "Luteinizing Hormone (LH)",
      "Prolactin",
      "Progesterone (Day 3)",
    ],
  },
  {
    name: "Emerald fertility profile (maxi)",
    items: [
      "Thyroid Stimulating Hormone (TSH)",
      "Estradiol",
      "Follicule Stimulating Hormone (FSH)",
      "Luteinizing Hormone (LH)",
      "Progesterone (Day 3)",
      "Prolactin",
      "Anti Mullerian Hormone (AMH)",
      "Progesterone (Day 21)",
    ],
  },
  {
    name: "PCOS(mini)",
    items: [
      "Fasting Blood Sugar (FBS)",
      "Total Cholesterol",
      "Follicule Stimulating Hormone (FSH)",
      "Luteinizing Hormone (LH)",
      "Testosterone (Total)",
      "Ultrasound Transvaginal",
    ],
  },
  {
    name: "PCOS(maxi)",
    items: [
      "Fasting Blood Sugar (FBS)",
      "Thyroid Stimulating Hormone (TSH)",
      "Estradiol",
      "Follicule Stimulating Hormone (FSH)",
      "Luteinizing Hormone (LH)",
      "Prolactin",
      "SHBG (Sex Hormone Binding Globulin)",
      "Dehydroepiandrosterone Sulphate (DHEAS)",
      "Free Androgen Index (FAI)",
      "Testosterone (Total)",
      "Transvaginal Ultrasound",
    ],
  },
  {
    name: "Cervical Cancer Screening ",
    items: ["Liquid Based Cytology (LBC)"],
  },
  {
    name: "Topaz fertility profile (mini)",
    items: [
      "Seminal Fluid Analysis (SFA)",
      "Semen: Microscopy, Culture & Sensitivity (MCS)",
    ],
  },

  {
    name: "Topaz fertility profile (maxi)",
    items: [
      "Follicule Stimulating Hormone (FSH)",
      "Luteinizing Hormone (LH)",
      "Prolactin",
      "Testosterone (Total)",
      "Seminal Fluid Analysis (SFA)",
      "Semen: Microscopy, Culture & Sensitivity (MCS)",
    ],
  },
  {
    name: "Vitality package (Basic)",
    items: [
      "Fasting Blood Sugar (FBS)",
      "Total Cholesterol",
      "Full Blood Count",
      "Urinalysis",
      "Liver Function Test (AST/ALT)",
      "Kidney Function Test (Urea/Creatinine)",
    ],
  },
  {
    name: "Topaz package (mini)",
    items: [
      "Fasting Blood Sugar (FBS)",
      "Lipid Profile (Lipogram)",
      "Uric Acid",
      "Full Blood Count",
      "Thyroid Stimulating Hormone (TSH)",
      "Prostate Specific Antigen (PSA)",
      "Stool Microscopy",
      "Urinalysis",
      "Liver Function Test (AST/ALT)",
      "Kidney Function Test (Urea/Creatinine)",
    ],
  },
  {
    name: "Topaz package (maxi)",
    items: [
      "HbA1C",
      "Inorganic Phosphate",
      "Lipid Profile (Lipogram)",
      "Liver Function Test",
      "Kidney Function Test",
      "Calcium",
      "Uric Acid",
      "Thyroid Function Test (Free T3, Free T4, TSH)",
      "Full Blood Count",
      "Prostate Specific Antigen (PSA)",
      "C-Reactive Protein (CRP)",
      "Hepatitis B Surface Antigen (HBsAg) Rapid",
      "HIV I & II Rapid",
      "Hepatitis C Virus Ab (Rapid)",
      "Stool Occult Blood",
      "Stool Microscopy",
      "Urinalysis",
    ],
  },
  {
    name: "Pre Employment",
    items: [
      "Sputum AFB - Tuberculosis test",
      "HIV I & II Rapid",
      "HBsAG",
      "Full Blood Count",
      "Genotype test",
      "Drug of Abuse",
      "Medical history & complete Examination",
    ],
  },
];

export const nigeriaStates = [
  {
    name: "Abia",
    capital: "Umuahia",
    region: "South East",
  },
  {
    name: "Adamawa",
    capital: "Yola",
    region: "North East",
  },
  {
    name: "Akwa Ibom",
    capital: "Uyo",
    region: "South South",
  },
  {
    name: "Anambra",
    capital: "Awka",
    region: "South East",
  },
  {
    name: "Bauchi",
    capital: "Bauchi",
    region: "North East",
  },
  {
    name: "Bayelsa",
    capital: "Yenagoa",
    region: "South South",
  },
  {
    name: "Benue",
    capital: "Makurdi",
    region: "North Central",
  },
  {
    name: "Borno",
    capital: "Maiduguri",
    region: "North East",
  },
  {
    name: "Cross River",
    capital: "Calabar",
    region: "South South",
  },
  {
    name: "Delta",
    capital: "Asaba",
    region: "South South",
  },
  {
    name: "Ebonyi",
    capital: "Abakaliki",
    region: "South East",
  },
  {
    name: "Edo",
    capital: "Benin City",
    region: "South South",
  },
  {
    name: "Ekiti",
    capital: "Ado-Ekiti",
    region: "South West",
  },
  {
    name: "Enugu",
    capital: "Enugu",
    region: "South East",
  },
  {
    name: "Gombe",
    capital: "Gombe",
    region: "North East",
  },
  {
    name: "Imo",
    capital: "Owerri",
    region: "South East",
  },
  {
    name: "Jigawa",
    capital: "Dutse",
    region: "North West",
  },
  {
    name: "Kaduna",
    capital: "Kaduna",
    region: "North West",
  },
  {
    name: "Kano",
    capital: "Kano",
    region: "North West",
  },
  {
    name: "Katsina",
    capital: "Katsina",
    region: "North West",
  },
  {
    name: "Kebbi",
    capital: "Birnin Kebbi",
    region: "North West",
  },
  {
    name: "Kogi",
    capital: "Lokoja",
    region: "North Central",
  },
  {
    name: "Kwara",
    capital: "Ilorin",
    region: "North Central",
  },
  {
    name: "Lagos",
    capital: "Ikeja",
    region: "South West",
  },
  {
    name: "Nasarawa",
    capital: "Lafia",
    region: "North Central",
  },
  {
    name: "Niger",
    capital: "Minna",
    region: "North Central",
  },
  {
    name: "Ogun",
    capital: "Abeokuta",
    region: "South West",
  },
  {
    name: "Ondo",
    capital: "Akure",
    region: "South West",
  },
  {
    name: "Osun",
    capital: "Osogbo",
    region: "South West",
  },
  {
    name: "Oyo",
    capital: "Ibadan",
    region: "South West",
  },
  {
    name: "Plateau",
    capital: "Jos",
    region: "North Central",
  },
  {
    name: "Rivers",
    capital: "Port Harcourt",
    region: "South South",
  },
  {
    name: "Sokoto",
    capital: "Sokoto",
    region: "North West",
  },
  {
    name: "Taraba",
    capital: "Jalingo",
    region: "North East",
  },
  {
    name: "Yobe",
    capital: "Damaturu",
    region: "North East",
  },
  {
    name: "Zamfara",
    capital: "Gusau",
    region: "North West",
  },
];
